### PR TITLE
Drive metadata

### PR DESCRIPTION
**Pull request by amboar**
This builds on #4 to mitigate drive polling and log spamming by nvmesensor when drive presence is incorrectly reported.

### CODE REVIEW

**Comment by amboar** [comment]
We need https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/48562/ as well to handle drives not being powered at standby.

**Comment by amboar** [comment]
This PR misses a hardware mapping between mux legs and drives on Flett, and so every second drive will fail to be monitored. I'll push an update shortly.

**Comment by amboar** [comment]
Fixed the mux leg mapping issue

**Review by spinler — APPROVED** [review]

**Comment by amboar** [comment]
Thanks @spinler !

**Pull request merged**
